Integrate API Token and Improve gmsaas commands with json format
Genymobile/bitrise-step-genymotion-cloud-saas-start pull request #17
Opened 2024-05-30 14:21 UTC by thomascarpentier

**Integrate API Token**

Now it's possible to use the API Token created in Cloud.geny.io in order to authenticate the user. 

**Add json format for gmsaas commands**

To avoid parsing output text, now we use the json output to retrieve instance details ( name, UUID and ADB serial ) 

* Add more tests to cover API Token

2024-05-31 12:57 UTC, lilinor commented on main.go
> +	if api_token != "" {
In the case the user inputs api_token, username & password, will it always run the gmsaas auth token command?

2024-05-31 12:58 UTC, lilinor commented on main.go
> +		abortf("Failed to log with gmsaas, error: error: %s | output: %s", cmd.Args, err, out)
Failed to log **in**

2024-05-31 13:06 UTC, lilinor commented on step.yml
> +  - gmsaas_version: "1.11.0"
If a new version of gmsaas is released > 1.11, will it still install 1.11.0 version?

2024-05-31 13:07 UTC, lilinor reviewed
I made some comments

2024-05-31 14:00 UTC, thomascarpentier commented on main.go
> +	if api_token != "" {
Yes, I prioritize the use of the api token. Username and Password will be removed in the future.

2024-05-31 14:02 UTC, thomascarpentier commented on step.yml
> +  - gmsaas_version: "1.11.0"
Yes, but the user can change it in the workflow. 
I can remove the default value, or I can keep it to avoid some errors due to a new gmsaas version. Let me know what you prefer ?

2024-06-21 14:45 UTC, lilinor commented on step.yml
> +  - gmsaas_version: "1.11.0"
Let's keep it to avoid some errors to new gmsaas version

2024-06-21 14:47 UTC, lilinor commented on step.yml
> +          Install a specific version of gmsaas, per default it will install the latest gmsaas compatible : 1.11.0
it will install the latest compatible gmsaas version

2024-06-21 14:48 UTC, lilinor requested changes
I've just changed slightly the wording in the gmsaas description

2024-06-21 15:06 UTC, merged